### PR TITLE
CI: Also run tests on PRs and add manual trigger

### PR DESCRIPTION
**Pull request by EwoutH**
Also run the CI test also when a PR is opened or modified, and add manual trigger to the UI with the [`workflow_dispatch`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) tag.

### CODE REVIEW

**Comment by JoelForamitti** [comment]
Hi, thanks for the PR. Could you elaborate on the advantage of the manual trigger? Does something speak against always running the test suite?

**Comment by EwoutH** [comment]
> Does something speak against always running the test suite?

Environment, but that's mostly the case for very large and very active projects with large CI cases.

This PR just _adds_ the possibility to also trigger a workflow manually, it's still run automatically on every PR and push.

**Comment by EwoutH** [comment]
When merging a PR, consider using the "Squash and Merge" button in GitHub. It will make the merge a lot cleaner in the git history (it doesn't create an additional merge commit)

See also the docs: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits

**Comment by JoelForamitti** [comment]
Got it. Thanks for your knowledge @EwoutH, it is very much appreciated!

**Pull request merged**
