### PR TITLE
simplified logic in torus grid

### PR DESCRIPTION
**Pull request by Tortar**
First of all, thank you for the programme! :-)

I noticed that the logic in the torus case grid was a little convoluted and so I simplified it: I tested the change with test_neighbors_with_torus() in the tests folder and everything seems alright. I also changed some intermediate lists in iterators, say to me if this is welcomed or you prefer lists over iterators

### CODE REVIEW

**Comment by Tortar** [comment]
Hey @JoelForamitti are you still mantaining the project? Because it seems a rather good one, would like to contribute :-)

**Comment by JoelForamitti** [comment]
Hi @Tortar! Thank you for the reminder, and glad that you like the project! I am quite confident that this month I will find some time to set up a new CI to test and merge your contributions!

Btw. I see that you added some new commits to this PR. Is it ready for review or do you plan some further changes?

**Comment by Tortar** [comment]
Think it's ready for review, I simplified some other part of the code but I think that it is good to open up a new PR for further changes

**Comment by JoelForamitti** [comment]
@Tortar i have created the github actions now. can you merge the main branch into this one? then the automatic tests should run!

**Pull request merged**
